package package ${packageName}.exception;

import io.quarkus.qeex.api.annotations.QeexConfig;
import io.quarkus.qeex.api.exceptions.QeexWebException;
import io.quarkus.qeex.api.interceptors.LanguageInterceptor;

import javax.annotation.processing.Generated;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

@ApplicationScoped
@Generated(value = "dev.queryable.QuexGenerator", date = "2023-05-04T12:08:56.235-0700", comments = "don't touch please")
public class ExceptionBundleImpl implements ExceptionBundle {

        // copied from application properties: qeex.project=FLW
        String classProjectName = "FLW";

        @Inject
        QeexConfig qeexConfig;

        @Inject
        LanguageInterceptor languageInterceptor;

        @Override
        public QeexWebException simpleException() {
                // from annotation  @QeexMessage(message = "prova")
                //this id IS AUTOMATICALLY GENERATED by method position inside interface
                int _id = 101;
                Integer code = null;
                String message = "prova";
                String language = null;
                return QeexWebException.builder(qeexConfig.get_project(classProjectName))
                    .code(_id)
                    .code(qeexConfig.get_code(_id, code))
                    .message(qeexConfig.get_message(_id, message, languageInterceptor.getLanguage()))
                    .language(qeexConfig.get_language(_id, languageInterceptor.getLanguage()));
        }

}